export const CHANNELS = {
  ADD: 'ADD_CHANNELS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  FETCH: 'FETCH_CHANNELS',
  TOGGLE_FETCHING: 'TOGGLE_FETCHING_CHANNELS',
};

export const CHANNEL = {
  ADD: 'ADD_CHANNEL',
};

export const CHAT = {
  SAVE_SETTINGS: 'SAVE_CHAT_SETTINGS',
  FETCH_SETTINGS: 'FETCH_CHAT_SETTINGS',
};