export const MESSAGES = {
  LOAD: 'MESSAGES_LOAD',
  LOAD_SUCCESS: 'MESSAGES_LOAD_SUCCESS',
  LOAD_FAIL: 'MESSAGES_LOAD_FAIL',

  ADD: 'ADD_MESSAGE',
};

export const INCOMING_MESSAGES = {
  ADD: 'ADD_INCOMING_MESSAGES',
  UPDATE: 'UPDATE_INCOMING_MESSAGE',
  FETCH: 'FETCH_INCOMING_MESSAGES',
  ADD_TO_INBOX: 'ADD_TO_INBOX_INCOMING_MESSAGE',
  UPDATE_FILTERS: 'UPDATE_FILTERS',
};

export const ASSIGNED_USER = {
  UPDATE: 'ASSIGNED_USER_UPDATE',
};

export const SELECT_CLIENT = 'SELECT_CLIENT';

export const INCOMING_MESSAGES_FOR_SELECTED_CLIENT = {
  ADD: 'ADD_INCOMING_MESSAGES_FOR_SELECTED_CLIENT',
};

export const CLIENT_DATA = {
  UPDATE: 'CLIENT_DATA_UPDATE',
  CHANGE_MESSAGES_STATUS: 'CHANGE_MESSAGES_STATUS',
};

export const SELECTED_CLIENT_UPDATE = 'SELECTED_CLIENT_UPDATE';

export const SELECTED_CLIENT_GET_INFO = 'SELECTED_CLIENT_GET_INFO';